
package com.sdk.wms.iml.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Ec", targetNamespace = "http://www.example.org/Ec/", wsdlLocation = "http://oms.imlb2c.com/default/svc/wsdl")
public class Ec_Service
    extends Service
{

    private final static URL EC_WSDL_LOCATION;
    private final static WebServiceException EC_EXCEPTION;
    private final static QName EC_QNAME = new QName("http://www.example.org/Ec/", "Ec");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://oms.imlb2c.com/default/svc/wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EC_WSDL_LOCATION = url;
        EC_EXCEPTION = e;
    }

    public Ec_Service() {
        super(__getWsdlLocation(), EC_QNAME);
    }

    public Ec_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EC_QNAME, features);
    }

    public Ec_Service(URL wsdlLocation) {
        super(wsdlLocation, EC_QNAME);
    }

    public Ec_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EC_QNAME, features);
    }

    public Ec_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ec_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Ec
     */
    @WebEndpoint(name = "EcSOAP")
    public Ec getEcSOAP() {
        return super.getPort(new QName("http://www.example.org/Ec/", "EcSOAP"), Ec.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Ec
     */
    @WebEndpoint(name = "EcSOAP")
    public Ec getEcSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/Ec/", "EcSOAP"), Ec.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EC_EXCEPTION!= null) {
            throw EC_EXCEPTION;
        }
        return EC_WSDL_LOCATION;
    }

}
