server:
  port: 11001

spring:
  profiles:
    active: sharding-databases
  application:
    name: sharding-jdbc-demo
  main:
    allow-bean-definition-overriding: true

zlt:
  datasource:
    ip: 172.10.10.135
    username: root
    password: 1q2w3e4r

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.sharding.demo.model
  global-config:
    db-config:
      id-type: ID_WORKER